name: Deploy SAGF Folder

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 4. Copy files to server (using scp-action for file transfer)
      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          # Source directory: the root folder of the repo
          source: "./"
          # *** TARGET CORRECTED TO MATCH NGINX ROOT ***
          target: "/var/www/sagf/"
          exclude: ".git, .github"
          overwrite: true

      # 5. SSH into server & deploy (cleanup, test, and restart)
      - name: SSH into server & deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            DEPLOY_PATH="/var/www/sagf/"
            
            # 1. Set correct file permissions for Nginx user (www-data)
            echo "Setting ownership and permissions on ${DEPLOY_PATH}..."
            sudo chown -R www-data:www-data ${DEPLOY_PATH}
            sudo chmod -R 755 ${DEPLOY_PATH}

            # 2. Test Nginx configuration before reloading/restarting
            echo "Testing Nginx configuration..."
            sudo nginx -t
            
            # Check the exit status of the previous command (nginx -t)
            if [ $? -eq 0 ]; then
                echo "Nginx config test passed. Proceeding with restart."
                
                # 3. Reload daemon and restart Nginx service
                sudo systemctl daemon-reload
                sudo systemctl restart nginx
                echo "Deployment to ${DEPLOY_PATH} and Nginx restart completed successfully."
            else
                echo "Nginx configuration test FAILED. Nginx service not restarted. Check logs."
                # Optionally, you can add 'exit 1' here to fail the GitHub Action job immediately
                exit 1 
            fi
